### PR TITLE
Changes to allow e.g. a subclass of a MultiParameter to work

### LINKED ISSUE #59: QCoDeS can't register proxy parameters based on parameter_class
My VNA, the Copper Mountain M5180, has qcodes parameters for each s-parameter, defined like
```
self.add_parameter(name='s11',
                           start=self.start(),
                           stop=self.stop(),
                           npts=self.npts(),
                           parameter_class=FrequencySweepMagPhase)
```
The instrument server and client don't have any problems with that parameter, but trying to add that the proxy parameter with `meas.register_parameter(vna.s21)` gives `ValueError: Can not register object of type <class 'method'>. Can only register a QCoDeS Parameter.`. It seems the client doesn't properly make that function a qcodes parameter when it's created.

### PR DESCRIPTION
**Pull request by ttshaw1**
Fixes #59 

I made changes to the server core and the client proxy files to broaden what types of parameters will work. I've been testing against the M5180 VNA driver and the sXX parameters which are defined by a `parameter_class` which is a subclass of a `MultiParameter` and both those fancy parameters and mundane `Parameter` parameters are working. It's mostly but not entirely hack-free and might cause memory issues for very large numbers of parameters. 

The particular instrument I'm testing on has a driver issue where the setpoints for sXX don't ever update, so e.g. changing the frequency range isn't reflected. I may fix the driver so that get_raw for that parameter will also update that parameter's setpoints. But as of right now that wouldn't be reflected in the client. I think this could be resolved by, when calling `client_vna.s11()`, instead of having `client_vna.get_raw()` only call `client_vna._remoteGet()` , call `client_vna._remoteGet()` and also `client_vna.updateFromBP()` (and I suppose refresh the blueprint). Up to you whether you think that's a good idea.

### CODE REVIEW

**Comment by ttshaw1** [comment]
I forgot to remove my quick-fix on line 453 for issue 53

**Comment by wpfff** [comment]
@ttshaw1 huh -- i totally missed this, somehow this does not show up in my notifications... I'll have a look ASAP (hopefully this weekend).
@marcosfrenkel could you maybe also take a peek?

**Comment by wpfff** [comment]
@ttshaw1  can you write a summary of what this is doing? I'm not sure i get it immediately. 

my original intuition would have been that we probably will need one type of ProxyParameter for each of the more advanced types of QCodes parameters -- is your idea that you want to automatically create a parameter that works for everything?

If that's true, then I'm a bit concerned that that is not explicit enough and opens a lot of paths for potential bugs.

some more explanation and docs, plus tests would be good...

**Comment by ttshaw1** [comment]
Sorry for the late reply. The essence of this is that, for each parameter, instead of passing just a parameter blueprint with a few select attributes of the parameters, the server passes a blueprint containing every picklable attribute including what the parent class of the parameter is. The client then uses that expanded blueprint to create a proxy parameter with the appropriate parent class. There's some logic required there to give that parent class' init() function the necessary arguments and then afterwards overwrite them. 

The example I was working against was the Copper Mountain M5180's s21() parameter, which is defined by a class FrequencySweepMagPhase with a MultiParameter parent class. FrequencySweepMagPhase's init arguments are different from those of MultiParameter. So the code I wrote creates a proxy parameter with parent class MultiParameter, figures out MultiParameter's required arguments, gets as many as possible from the blueprint and makes dummy values for the rest, and calls the MultiParameter init function, then overwrites things the MultiParameter init function changed with values from the blueprint. This way MultiParameter init() can do the things its required to do in order for the proxy parameter to be a valid qcodes parameter, but the values from the parameter on the server are restored afterwards.

**Pull request closed without merging**
