### PR TITLE
Parameter deletion bugfix.

### PR DESCRIPTION
**Pull request by pfafflabatuiuc**
Also fixed bug when loading parameters from file crashing a different parametermanager window.

### CODE REVIEW

**Comment by wpfff** [comment]
@marcosfrenkel can you remind me what this PR fixes exactly?

**Comment by marcosfrenkel** [comment]
> @marcosfrenkel can you remind me what this PR fixes exactly?

This was a bugfix I found. When deleting a parameter (from code or other parameter manager), the parameter manager wouldn't delete it by itself. 

Also found another bug with the loading of parameters that should also be fixed.

**Comment by wpfff** [comment]
did you test everything? (or: how confident are you that i can merge without testing it and it won't break anything? :))

**Comment by marcosfrenkel** [comment]
> did you test everything? (or: how confident are you that i can merge without testing it and it won't break anything? :))

I don't think it will break anything, but just to be safe I'll do another round of testing tonight.

**Comment by pfafflabatuiuc** [comment]
I heavily tested the parameter manager and found 4 extra bugs that did not seem related to this particular bugfix. I managed to fix 2 of them. However, everything seems very stable and should not crash with normal use.

Fixed bugs:

- When opening a parameter manager in a directory that contained a previously saved state of it, the parameter manager loaded up the state, but it didn't show the parameters in the GUI. I fixed it by adding an update to the launching script.
- in client/proxy.py in line 242 it seemed to be deleting the wrong variable (from pn to k). It made the parameter manager crash sometimes because it could not find pn.

Unfixed bugs:

- Very rarely (sometimes when creating a new parameter, others when deleting it. Could not find a way of reliably triggering it.) the parameter manager would go into an infinite recursive loop and crash.
- I test real-time updates by opening different windows of the parameter manager. When I create a parameter with a unit, then delete it and create a new parameter of the same name but different unit, the second parameter manager will show the old unit instead of the new one. Could not really tell why this was happening. This seems to be a minor bug since it does not make anything break. The parameter still gets real-time updates and gets properly deleted and saved (the instrumentserver holds the correct new unit).

Should I open issues for these 2 bugs?

**Comment by wpfff** [comment]
yes, it'd be great open issues for those. 
but it's important to figure out how to reproduce them :)

**Pull request merged**
