### PR TITLE
Read only server and new logger class

### PR DESCRIPTION
**Pull request by Zack-Code-UIUC**
Server: 
- The server now has the ability to go into a read-on mode, where other clients cannot modify the data contained in the server.
- The server also has the functionality of broadcasting new changes happening to the server's parameters.

logger:
- A new logger class is written and has replaced the old logger class. 
- The logger class now has the ability to listen to broadcasts. 
- Added the ability for the logger to check if parameters' values are within bounds and log an error message, if not.

The log file format:
- The ":" symbol now is replaced with the "|" symbol.

### CODE REVIEW

**Comment by wpfff** [comment]
@Zack-Code-UIUC and @marcosfrenkel can you guys let me know how to test this? 
(what command/code do i need to run, etc)

**Comment by Zack-Code-UIUC** [comment]
@wpfff Here are the two python scripts that can be used to test the server and logger. Both of them are in the testing_files.zip. 
[testing_files.zip](https://github.com/toolsforexperiments/instrumentserver/files/10128113/testing_files.zip)

To start testing, extract them into a testing directory. 

The file init_script.py is used for initializing the dummy server, which contains an instrument with five parameters. To start the server, use the command:
_instrumentserver -i init_script.py_
The new feature read_only mode of the server can be activated by running the command:
_instrumentserver -i init_script.py -r True_

To start the logger, run the command:
_instrumentserver-dashboardlogger_
This command starts the logger, which by default will search for the file _instrumentserver-dashboard-cfg.py_ in the root directory. The file _instrumentserver-dashboard-cfg.py_ contains the configuration for the logger.

**Comment by wpfff** [comment]
@marcosfrenkel this one's yours now -- lets see if we can make this useable with instrument telemetry by the end of the summer.

**Comment by marcosfrenkel** [comment]
Went with a different architecture for this idea

**Pull request closed without merging**
